entries:
- title: Sidebar
  levels: one
  folders:

  - title: Elements
    output: web
    folderitems:
    - title: Buttons
      url: /buttons
      output: web
    - title: Details and Summary
      url: /details-summary
      output: web
    - title: SVG
      url: /svg
      output: web
    - title: Menu
      url: /menu
      output: web
